import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

// Define styles specifically for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#cccccc',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    color: '#333333',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#666666',
  },
  scoreCard: {
    backgroundColor: '#f3f4f6',
    padding: 15,
    borderRadius: 5,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scoreText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  questionContainer: {
    marginBottom: 15,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  questionText: {
    fontSize: 12,
    marginBottom: 5,
    fontWeight: 'bold',
    color: '#111',
  },
  answerRow: {
    fontSize: 10,
    marginBottom: 3,
    flexDirection: 'row',
  },
  correctLabel: { color: '#059669', marginRight: 5 }, // Green
  wrongLabel: { color: '#dc2626', marginRight: 5 },   // Red
  explanation: {
    marginTop: 5,
    fontSize: 10,
    color: '#4f46e5', // Indigo
    fontStyle: 'italic',
    backgroundColor: '#eef2ff',
    padding: 5,
  },
});

export const QuizPDFDocument = ({ questions, userAnswers, stats, topic }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>GeminiQuiz.ai Report</Text>
        <Text style={styles.subtitle}>Domain: {topic} | Date: {new Date().toLocaleDateString()}</Text>
      </View>

      {/* Score Summary */}
      <View style={styles.scoreCard}>
        <Text style={styles.scoreText}>Score: {stats.correct} / {stats.total}</Text>
        <Text style={styles.scoreText}>Accuracy: {Math.round((stats.correct/stats.total)*100)}%</Text>
      </View>

      {/* Questions List */}
      {questions.map((q, idx) => {
        const userAns = userAnswers[q.id];
        const isCorrect = userAns === q.correctAnswer;
        
        return (
          <View key={q.id} style={styles.questionContainer}>
            <Text style={styles.questionText}>{idx + 1}. {q.question}</Text>
            
            <Text style={styles.answerRow}>
              <Text style={{color: '#666'}}>Your Answer: </Text>
              <Text style={isCorrect ? styles.correctLabel : styles.wrongLabel}>
                {userAns || "Skipped"}
              </Text>
            </Text>

            <Text style={styles.answerRow}>
              <Text style={{color: '#666'}}>Correct Answer: </Text>
              <Text style={styles.correctLabel}>{q.correctAnswer}</Text>
            </Text>

            <Text style={styles.explanation}>
              Insight: {q.explanation}
            </Text>
          </View>
        );
      })}
      
      <Text style={{ textAlign: 'center', fontSize: 10, color: '#999', marginTop: 20 }}>
        Generated by GeminiQuiz.ai
      </Text>
    </Page>
  </Document>
);