import React, { useMemo } from 'react';
import { Trophy, RefreshCw, BarChart2, CheckCircle, XCircle, Printer } from 'lucide-react';

// --- Merged PrintableReport Component ---
// This component is hidden on screen but visible when printing
const PrintableReport = ({ questions, userAnswers, stats, topic }) => {
  return (
    <div className="hidden print:block absolute top-0 left-0 w-full bg-white z-[9999] p-8 text-slate-900">
      
      {/* Header */}
      <div className="border-b-2 border-slate-300 pb-6 mb-8">
        <h1 className="text-4xl font-bold text-slate-900 mb-2">GeminiQuiz.ai Report</h1>
        <div className="flex justify-between text-slate-600 font-medium">
          <span>Domain: {topic}</span>
          <span>Date: {new Date().toLocaleDateString()}</span>
        </div>
      </div>

      {/* Score Summary */}
      <div className="bg-slate-100 border border-slate-200 rounded-xl p-6 mb-8 flex items-center justify-between">
        <div>
          <span className="block text-sm uppercase tracking-wide text-slate-500 font-bold">Total Score</span>
          <span className="text-3xl font-bold text-indigo-700">{stats.correct} / {stats.total}</span>
        </div>
        <div>
          <span className="block text-sm uppercase tracking-wide text-slate-500 font-bold text-right">Accuracy</span>
          <span className="text-3xl font-bold text-slate-800">{Math.round((stats.correct/stats.total)*100)}%</span>
        </div>
      </div>

      {/* Questions List */}
      <div className="space-y-6">
        <h3 className="font-bold text-xl flex items-center gap-2 border-b border-slate-200 pb-2">
          <BarChart2 className="w-5 h-5" /> Detailed Analysis
        </h3>

        {questions.map((q, idx) => {
          const userAns = userAnswers[q.id];
          const isCorrect = userAns === q.correctAnswer;
          const isSkipped = !userAns;

          return (
            <div key={q.id} className="break-inside-avoid border-b border-slate-100 pb-4">
              <div className="flex gap-3">
                <div className="mt-1">
                  {isCorrect ? (
                    <CheckCircle className="w-5 h-5 text-green-600" />
                  ) : isSkipped ? (
                    <div className="w-5 h-5 text-slate-400 font-bold">?</div>
                  ) : (
                    <XCircle className="w-5 h-5 text-red-600" />
                  )}
                </div>
                <div className="flex-1">
                  <h4 className="font-bold text-slate-800 mb-2">
                    {idx + 1}. {q.question}
                  </h4>
                  
                  <div className="grid grid-cols-2 gap-4 text-sm mb-2">
                    <div className={isCorrect ? "text-green-700 font-semibold" : "text-red-700 font-semibold"}>
                      Your Answer: <span className="text-slate-900 font-normal">{userAns || "Skipped"}</span>
                    </div>
                    <div className="text-indigo-700 font-semibold">
                      Correct: <span className="text-slate-900 font-normal">{q.correctAnswer}</span>
                    </div>
                  </div>

                  <p className="text-sm text-slate-600 italic bg-slate-50 p-2 rounded border-l-4 border-indigo-300">
                    Insight: {q.explanation}
                  </p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <div className="mt-8 text-center text-slate-400 text-sm">
        Generated by GeminiQuiz.ai
      </div>
    </div>
  );
};

// --- Simple Pie Chart Component ---
const PerformanceChart = ({ correct, total }) => {
  const percentage = Math.round((correct / total) * 100);
  const radius = 40;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (percentage / 100) * circumference;
  
  let color = 'text-red-500';
  if (percentage >= 70) color = 'text-green-500';
  else if (percentage >= 40) color = 'text-yellow-500';

  return (
    <div className="relative w-40 h-40 flex items-center justify-center">
      <svg className="transform -rotate-90 w-full h-full">
        <circle cx="80" cy="80" r={radius} stroke="currentColor" strokeWidth="10" fill="transparent" className="text-slate-200" />
        <circle cx="80" cy="80" r={radius} stroke="currentColor" strokeWidth="10" fill="transparent" strokeDasharray={circumference} strokeDashoffset={strokeDashoffset} strokeLinecap="round" className={`${color} transition-all duration-1000 ease-out`} />
      </svg>
      <div className="absolute flex flex-col items-center">
        <span className={`text-3xl font-bold ${color}`}>{percentage}%</span>
        <span className="text-xs text-slate-500 font-medium">Accuracy</span>
      </div>
    </div>
  );
};

export default function ResultDashboard({ questions, userAnswers, topic, onRestart }) {
  // Calculate Stats
  const stats = useMemo(() => {
    let correct = 0;
    let skipped = 0;
    questions.forEach(q => {
      const userAns = userAnswers[q.id];
      if (!userAns) skipped++;
      else if (userAns === q.correctAnswer) correct++;
    });
    return { correct, skipped, total: questions.length, incorrect: questions.length - correct - skipped };
  }, [questions, userAnswers]);

  return (
    <>
      {/* This component is hidden normally (display:none) but becomes visible 
        when the browser print dialog opens due to the 'print:block' class 
        inside the component itself.
      */}
      <PrintableReport questions={questions} userAnswers={userAnswers} stats={stats} topic={topic} />

      <div className="animate-fade-in space-y-8 pb-12 print:hidden">
        
        {/* Top Summary Section */}
        <div className="grid md:grid-cols-3 gap-6">
          <div className="md:col-span-2 bg-white rounded-2xl shadow-sm border border-slate-200 p-8 flex flex-col md:flex-row items-center gap-8">
            <div className="shrink-0"><PerformanceChart correct={stats.correct} total={stats.total} /></div>
            <div className="flex-1 text-center md:text-left space-y-2">
              <h2 className="text-2xl font-bold text-slate-900">Quiz Analysis</h2>
              <p className="text-slate-500">You completed the <strong className="text-slate-700">{topic}</strong> assessment.</p>
              <div className="flex gap-4 justify-center md:justify-start mt-4">
                <div className="px-4 py-2 bg-green-50 rounded-lg border border-green-100 text-green-700 font-bold">{stats.correct} Correct</div>
                <div className="px-4 py-2 bg-red-50 rounded-lg border border-red-100 text-red-700 font-bold">{stats.incorrect} Wrong</div>
              </div>
            </div>
          </div>

          <div className="bg-gradient-to-br from-indigo-600 to-violet-700 rounded-2xl shadow-lg p-8 text-white flex flex-col justify-center items-center text-center">
             <Trophy className="w-12 h-12 mb-4 text-yellow-300" />
             
             {/* RESTART BUTTON */}
             <button onClick={onRestart} className="w-full py-2 mb-3 bg-white text-indigo-600 font-bold rounded-xl hover:bg-indigo-50 transition-colors flex items-center justify-center gap-2">
               <RefreshCw className="w-4 h-4" /> New Test
             </button>

             {/* PRINT / SAVE PDF BUTTON */}
             <button 
               onClick={() => window.print()}
               className="w-full py-2 bg-indigo-500 text-white font-bold rounded-xl hover:bg-indigo-400 transition-colors flex items-center justify-center gap-2"
             >
               <Printer className="w-4 h-4" /> Save as PDF
             </button>

          </div>
        </div>

        {/* Detailed Review Table */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
          <div className="p-6 border-b border-slate-100 bg-slate-50">
            <h3 className="font-bold text-lg text-slate-800 flex items-center gap-2">
              <BarChart2 className="w-5 h-5 text-indigo-500" /> Detailed Insight
            </h3>
          </div>
          
          <div className="divide-y divide-slate-100">
            {questions.map((q, idx) => {
              const userAns = userAnswers[q.id];
              const isCorrect = userAns === q.correctAnswer;
              return (
                <div key={q.id} className="p-6 hover:bg-slate-50 transition-colors">
                  <div className="flex gap-4">
                    <div className="shrink-0 mt-1">
                      {isCorrect ? <CheckCircle className="w-6 h-6 text-green-500" /> : <XCircle className="w-6 h-6 text-red-500" />}
                    </div>
                    <div className="space-y-2 flex-1">
                      <h4 className="font-medium text-slate-900"><span className="text-slate-400 mr-2">#{idx + 1}</span>{q.question}</h4>
                      <p className="text-sm text-slate-600 bg-indigo-50/50 p-3 rounded-lg"><span className="font-bold text-indigo-600">Explanation:</span> {q.explanation}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </>
  );
}